services:
  - type: web
    name: demoRIP
    runtime: node
    buildCommand: npm install; npm run build
    staticPublishPath: dist/demoRIP/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
